import { definePost } from "./post.js";

export const postFixtures = Object.freeze([
  definePost({
    slug: "understanding-money-and-myself",
    status: "published",
    publishedAt: "2026-09-08T09:00:00+09:00",
    updatedAt: "2026-09-08T09:00:00+09:00",
    category: "경제",
    format: "긴 글",
    title: "돈을 이해한다는 것과, 나를 이해하는 것",
    excerpt: "돈을 공부할수록 결국 사람을 이해하게 된다. 숫자와 시장의 흐름 너머에는 언제나 선택을 하는 사람들이 있고, 그 선택은 각자의 세계관에서 비롯된다.",
    basis: "2026년 9월 경제 공부 기록",
    readingTimeMinutes: 14,
    tags: ["자산", "행동경제학", "자기이해"],
    sources: [],
    body: [
      { type: "paragraph", text: "돈을 공부하기 시작했을 때는 숫자를 더 잘 읽고 싶었다. 금리, 물가, 자산 가격처럼 서로 얽힌 지표를 이해하면 선택도 쉬워질 거라 생각했다." },
      { type: "heading", text: "숫자 뒤에는 선택이 있다" },
      { type: "paragraph", text: "같은 정보를 보고도 사람마다 전혀 다른 결정을 내린다. 무엇을 중요하게 생각하는지, 손실을 어떻게 받아들이는지에 따라 숫자의 의미가 달라지기 때문이다." },
      { type: "quote", text: "돈에 관한 선택을 돌아보는 일은 내가 무엇을 두려워하고 원하는지 살펴보는 일이기도 하다." },
      { type: "paragraph", text: "그래서 이 공부의 목표를 정답 찾기보다 판단 기준을 기록하는 것으로 바꾸었다. 시간이 지난 뒤 선택과 결과를 함께 돌아보기 위해서다." },
    ],
    seo: { title: "돈을 이해한다는 것과, 나를 이해하는 것", description: "돈과 선택의 관계를 행동경제학과 자기이해의 관점에서 기록합니다." },
  }),
  definePost({
    slug: "walking-and-ideas",
    status: "published",
    publishedAt: "2026-09-06T09:00:00+09:00",
    updatedAt: "2026-09-06T09:00:00+09:00",
    category: "관찰",
    format: "짧은 기록",
    title: "오늘의 관찰: 좋은 아이디어는 산책 중에 찾아온다",
    excerpt: "책상 앞에서 해결되지 않던 문제가, 걷는 동안에 갑자기 풀리는 순간이 있다. 몸이 움직일 때 생각도 함께 움직이기 때문일 것이다.",
    basis: "2026년 9월 개인 관찰 기록",
    readingTimeMinutes: 3,
    tags: ["산책", "아이디어", "일상"],
    sources: [],
    body: [
      { type: "paragraph", text: "오래 붙잡고 있던 문제를 잠시 내려놓고 걸었다. 해결하려 애쓰지 않았는데도 서로 떨어져 있던 생각이 자연스럽게 이어졌다." },
      { type: "heading", text: "생각을 밀어붙이지 않는 시간" },
      { type: "paragraph", text: "산책의 장점은 새로운 정보를 더하는 데 있지 않았다. 이미 머릿속에 있던 생각들이 다른 순서로 놓일 여유를 만드는 데 있었다." },
      { type: "paragraph", text: "다음에도 같은 상황이 오면 화면을 더 오래 바라보기보다 짧게 걷고 돌아와 보려고 한다." },
    ],
    seo: { title: "좋은 아이디어는 산책 중에 찾아온다", description: "걷는 동안 생각이 움직이는 순간을 짧게 기록합니다." },
  }),
  definePost({
    slug: "muji-aluminum-pen",
    status: "published",
    publishedAt: "2026-09-04T09:00:00+09:00",
    updatedAt: "2026-09-04T09:00:00+09:00",
    category: "리뷰",
    format: "사용기",
    title: "오래 쓰는 기분이 좋은, 무인양품 알루미늄 볼펜",
    excerpt: "화려하진 않지만 매일 손이 가는 물건이 있다. 단순함 속에서 오래 쓰는 물건이 주는 만족을 기록한다.",
    basis: "2026년 9월 직접 사용 경험",
    readingTimeMinutes: 6,
    tags: ["무인양품", "문구", "오래쓰는물건"],
    sources: [],
    body: [
      { type: "paragraph", text: "이 글은 제품 사양을 비교하는 구매 안내보다, 실제로 자주 사용하게 된 이유를 남기는 사용 기록에 가깝다." },
      { type: "heading", text: "손에 남는 감각" },
      { type: "paragraph", text: "표면이 단단하고 장식이 적어서 책상 위 어느 물건과도 크게 충돌하지 않는다. 가벼운 필기보다 천천히 메모할 때 특히 손이 자주 갔다." },
      { type: "heading", text: "추천하기 전에 남길 것" },
      { type: "list", items: ["오래 필기할 때의 피로감은 사람마다 다를 수 있다.", "리필과 정확한 모델 정보는 구매 시점의 공식 판매처에서 다시 확인해야 한다.", "이 평가는 한 달 동안 개인적으로 사용한 경험을 기준으로 한다."] },
    ],
    seo: { title: "무인양품 알루미늄 볼펜 사용기", description: "매일 손이 가는 알루미늄 볼펜의 사용 경험을 기록합니다." },
  }),
  definePost({
    slug: "questions-that-matter-with-ai",
    status: "published",
    publishedAt: "2026-09-01T09:00:00+09:00",
    updatedAt: "2026-09-01T09:00:00+09:00",
    category: "기술",
    format: "링크 노트",
    title: "AI를 도구로 쓸 때 더 중요해지는 질문",
    excerpt: "도구가 바뀌어도 문제를 정의하는 사람의 역할은 남는다.",
    basis: "2026년 9월 도구 활용 학습 기록",
    readingTimeMinutes: 4,
    tags: ["AI", "도구", "일"],
    sources: [
      { title: "Model guidance", publisher: "OpenAI Developers", url: "https://developers.openai.com/api/docs/guides/latest-model", accessedAt: "2026-09-09T09:00:00+09:00" },
    ],
    body: [
      { type: "paragraph", text: "AI가 답을 빠르게 만드는 도구라면, 사람에게 남는 일은 무엇을 물어야 하는지 정하는 일이다. 원하는 결과가 모호하면 빠른 답도 쉽게 엉뚱한 방향으로 간다." },
      { type: "heading", text: "질문 전에 정리할 것" },
      { type: "list", items: ["어떤 결과가 필요한가", "지켜야 할 조건은 무엇인가", "무엇을 근거로 완료를 판단할 것인가"] },
      { type: "paragraph", text: "도구의 성능을 기대하기 전에 목적, 제약, 성공 기준을 적어보면 결과를 비교하고 고치기도 쉬워진다." },
    ],
    seo: { title: "AI를 도구로 쓸 때 더 중요해지는 질문", description: "AI 시대에도 문제를 정의하는 사람의 역할이 중요한 이유를 기록합니다." },
  }),
]);
