import { definePost } from "./post.js";

export const postFixtures = Object.freeze([
  definePost({
    slug: "understanding-money-and-myself",
    status: "published",
    publishedAt: "2026-09-08T09:00:00+09:00",
    updatedAt: "2026-09-08T09:00:00+09:00",
    category: "경제",
    format: "긴 글",
    title: "돈을 이해한다는 것과, 나를 이해하는 것",
    excerpt: "돈을 공부할수록 결국 사람을 이해하게 된다. 숫자와 시장의 흐름 너머에는 언제나 선택을 하는 사람들이 있고, 그 선택은 각자의 세계관에서 비롯된다.",
    readingTimeMinutes: 14,
    tags: ["자산", "행동경제학", "자기이해"],
    sources: [],
    seo: { title: "돈을 이해한다는 것과, 나를 이해하는 것", description: "돈과 선택의 관계를 행동경제학과 자기이해의 관점에서 기록합니다." },
  }),
  definePost({
    slug: "walking-and-ideas",
    status: "published",
    publishedAt: "2026-09-06T09:00:00+09:00",
    updatedAt: "2026-09-06T09:00:00+09:00",
    category: "관찰",
    format: "짧은 기록",
    title: "오늘의 관찰: 좋은 아이디어는 산책 중에 찾아온다",
    excerpt: "책상 앞에서 해결되지 않던 문제가, 걷는 동안에 갑자기 풀리는 순간이 있다. 몸이 움직일 때 생각도 함께 움직이기 때문일 것이다.",
    readingTimeMinutes: 3,
    tags: ["산책", "아이디어", "일상"],
    sources: [],
    seo: { title: "좋은 아이디어는 산책 중에 찾아온다", description: "걷는 동안 생각이 움직이는 순간을 짧게 기록합니다." },
  }),
  definePost({
    slug: "muji-aluminum-pen",
    status: "published",
    publishedAt: "2026-09-04T09:00:00+09:00",
    updatedAt: "2026-09-04T09:00:00+09:00",
    category: "리뷰",
    format: "사용기",
    title: "오래 쓰는 기분이 좋은, 무인양품 알루미늄 볼펜",
    excerpt: "화려하진 않지만 매일 손이 가는 물건이 있다. 단순함 속에서 오래 쓰는 물건이 주는 만족을 기록한다.",
    readingTimeMinutes: 6,
    tags: ["무인양품", "문구", "오래쓰는물건"],
    sources: [],
    seo: { title: "무인양품 알루미늄 볼펜 사용기", description: "매일 손이 가는 알루미늄 볼펜의 사용 경험을 기록합니다." },
  }),
  definePost({
    slug: "questions-that-matter-with-ai",
    status: "published",
    publishedAt: "2026-09-01T09:00:00+09:00",
    updatedAt: "2026-09-01T09:00:00+09:00",
    category: "기술",
    format: "링크 노트",
    title: "AI를 도구로 쓸 때 더 중요해지는 질문",
    excerpt: "도구가 바뀌어도 문제를 정의하는 사람의 역할은 남는다.",
    readingTimeMinutes: 4,
    tags: ["AI", "도구", "일"],
    sources: [],
    seo: { title: "AI를 도구로 쓸 때 더 중요해지는 질문", description: "AI 시대에도 문제를 정의하는 사람의 역할이 중요한 이유를 기록합니다." },
  }),
]);
